### PR TITLE
Add tabs for graphs on choral page

### PR DESCRIPTION
**Pull request by jboretsky**
This creates tabs for each output key that has a numerical value from the chorals function. Each tab gets it's own epoch graph and they all update in parallel.

### CODE REVIEW

**Comment by jboretsky** [comment]
image

**Comment by jboretsky** [comment]
All tabs for the weather samples look like solid bars because the data is not changing over the short amount of time we show. If we could display the time range over a week, it would fluctuate a lot.

**Comment by cpjk** [comment]
:eyes: looking at this now

**Comment by andreirtaylor** [comment]
Would be nice if one of the graphs was showing on startup

**Comment by jboretsky** [comment]
sure I can add that

**Comment by cpjk** [comment]
code looks :+1:

**Comment by andreirtaylor** [comment]
Also is there a way to do evenly spaced tabs?
So that all the tabs are evenly spaced across the top of the graph

**Comment by cpjk** [comment]
> Also is there a way to do evenly spaced tabs?
> So that all the tabs are evenly spaced across the top of the graph

I think it looks fine like this.

**Pull request merged**
