### PR TITLE
Fix footer

### PR DESCRIPTION
**Pull request by james-woo**

### CODE REVIEW

**Comment by jboretsky** [comment]
I think it should be the way it was before, were you having problems with it that way?

**Comment by jboretsky** [comment]
Otherwise it'll just be at the bottom of the content, wherever that is, so it can look like this, which is kinda weird

image

**Comment by jboretsky** [comment]
I think it should be centered at the bottom, maybe we should have a footer area, with links to our team page and some other stuff as well

**Comment by james-woo** [comment]
I wanted this as well, but it covers some stuff (for example, if you have a large list of chorals). I will look into a real footer that covers the whole bottom of the page.

**Comment by james-woo** [comment]
I think it looks a lot better now
image

**Comment by jboretsky** [comment]
Yep looks awesome! Gonna merge it

**Pull request merged**
